name: Telegram Bot 24/7
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.12"}
      - run: pip install -r requirements.txt
      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
